# Generated by Django 4.1.7 on 2024-05-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("field_type", models.CharField(max_length=50)),
                ("required", models.BooleanField(default=True)),
                ("choices", models.TextField(blank=True)),
            ],
        ),
    ]
