# Generated by Django 5.0.6 on 2024-06-11 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("select", "Select"),
                            ("checkbox", "Checkbox"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Idioma",
                "verbose_name_plural": "Idiomas",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Lema",
            fields=[
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Lema",
                    ),
                ),
                (
                    "regular_form",
                    models.CharField(max_length=150, verbose_name="Forma regular"),
                ),
            ],
            options={
                "verbose_name": "Lema",
                "verbose_name_plural": "Lemas",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="TypePronunciation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Tipo de pronunciación",
                "verbose_name_plural": "Tipos de pronunciación",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="WordType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Tipo de palabra"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Palabra",
                "verbose_name_plural": "Tipos de Palabra",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Meaning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="Acepción")),
                ("index", models.IntegerField(default=0, verbose_name="Índice")),
                (
                    "mcer",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        default=("A1", "A1"),
                        max_length=5,
                        verbose_name="MCER",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="core/meaning/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "lema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.lema"
                    ),
                ),
                (
                    "word_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.wordtype",
                        verbose_name="Tipo de palabra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acepción",
                "verbose_name_plural": "Acepciones",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Orthography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "syllabic_division",
                    models.CharField(max_length=150, verbose_name="División silábica"),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="Observación"),
                ),
                (
                    "lema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.lema"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ortografía",
                "verbose_name_plural": "Ortografías",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="ImageOrthography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="core/orthography/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "orthography",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.orthography",
                        verbose_name="Ortografía",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de la ortografía",
                "verbose_name_plural": "Imagenes de la ortografía",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="TranslationMeaning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="Traducción")),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.language",
                        verbose_name="Idioma",
                    ),
                ),
                (
                    "meaning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.meaning",
                        verbose_name="Acepción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traducción",
                "verbose_name_plural": "Traducciones",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Pronunciation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Pronunciación"),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Variante"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="Observación"),
                ),
                (
                    "prosodic_variant",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Variante Prosódica",
                    ),
                ),
                (
                    "variant_observation",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Observación Variante Prosódica",
                    ),
                ),
                (
                    "lema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.lema"
                    ),
                ),
                (
                    "type_pronunciation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.typepronunciation",
                        verbose_name="Tipo de pronunciación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pronunciación",
                "verbose_name_plural": "Pronunciaciones",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Subgroupword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("select", "Select"),
                            ("checkbox", "Checkbox"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("morph", "Morfología"), ("sintx", "Sintaxis")],
                        max_length=50,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.subgroupword",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.formfield",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgroups",
                        to="core.wordtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Grupo",
                "verbose_name_plural": "Sub Grupos",
                "ordering": ("id",),
            },
        ),
    ]
