# Generated by Django 5.0.6 on 2024-06-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subgroupword",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                ],
                max_length=20,
            ),
        ),
    ]
