# Generated by Django 5.0.6 on 2024-06-12 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_subgroupword_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeaningSubGroupWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "meaning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.meaning"
                    ),
                ),
                (
                    "sub_group_word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.subgroupword",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aception Sub Group",
                "verbose_name_plural": "Aception Sub Groups",
                "ordering": ("id",),
            },
        ),
        migrations.DeleteModel(name="FormField",),
    ]
