# Generated by Django 5.0.6 on 2024-06-12 01:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_meaningsubgroupword_delete_formfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meaningsubgroupword",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=150,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
