# Generated by Django 4.1.7 on 2024-05-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_formfield_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                ],
                max_length=20,
            ),
        ),
    ]
