# Generated by Django 5.0.6 on 2024-06-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_subgroupword_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="meaningsubgroupword",
            name="value",
            field=models.CharField(default="", max_length=255),
        ),
    ]
