# Generated by Django 5.0.6 on 2024-06-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_value_formfieldoption_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfieldoption",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                ],
                default="test",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formfieldoption",
            name="required",
            field=models.BooleanField(default=True),
        ),
    ]
