# Generated by Django 5.0.6 on 2024-06-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_meaningsubgroupword_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroupword",
            name="add_traduction",
            field=models.BooleanField(default=False),
        ),
    ]
